import 'package:flutter/foundation.dart';
import 'package:flowtill/models/order_activity.dart';
import 'package:flowtill/services/order_activity_repository.dart';

class OrderHistoryProvider with ChangeNotifier {
  final _activityRepository = OrderActivityRepository();

  List<OrderActivity> _currentOrderHistory = [];
  bool _isLoadingHistory = false;
  String? _historyError;

  List<OrderActivity> get currentOrderHistory => _currentOrderHistory;
  bool get isLoadingHistory => _isLoadingHistory;
  String? get historyError => _historyError;

  /// Load history for the current order
  Future<void> loadHistoryForOrder(String orderId) async {
    debugPrint('🔄 OrderHistoryProvider: Loading history for order $orderId');

    _isLoadingHistory = true;
    _historyError = null;
    notifyListeners();

    try {
      final activities = await _activityRepository.getHistoryForOrder(orderId);
      _currentOrderHistory = activities;
      
      debugPrint('✅ Loaded ${activities.length} history entries');
    } catch (e) {
      _historyError = 'Failed to load history: ${e.toString()}';
      debugPrint('❌ Error loading history: $e');
    } finally {
      _isLoadingHistory = false;
      notifyListeners();
    }
  }

  /// Clear history for the current order (called when order is completed/paid)
  Future<void> clearHistoryForOrder(String orderId) async {
    debugPrint('🗑️ OrderHistoryProvider: Clearing history for order $orderId');

    try {
      await _activityRepository.clearHistoryForOrder(orderId);
      _currentOrderHistory = [];
      
      debugPrint('✅ History cleared');
      notifyListeners();
    } catch (e) {
      debugPrint('❌ Error clearing history: $e');
    }
  }

  /// Log an action to the current order's history
  Future<void> logOrderAction({
    required String outletId,
    required String orderId,
    String? tableId,
    String? staffId,
    required String actionType,
    required String actionDescription,
    Map<String, dynamic>? meta,
  }) async {
    debugPrint('📝 OrderHistoryProvider: Logging action: $actionType');

    try {
      // Save to Supabase
      await _activityRepository.logAction(
        outletId: outletId,
        orderId: orderId,
        tableId: tableId,
        staffId: staffId,
        actionType: actionType,
        actionDescription: actionDescription,
        meta: meta,
      );

      // Add to local list for immediate UI update (without ID since it's generated by DB)
      final newActivity = OrderActivity(
        id: 'temp-${DateTime.now().millisecondsSinceEpoch}',
        outletId: outletId,
        orderId: orderId,
        tableId: tableId,
        staffId: staffId,
        actionType: actionType,
        actionDescription: actionDescription,
        meta: meta,
        createdAt: DateTime.now(),
      );

      _currentOrderHistory.add(newActivity);
      notifyListeners();

      debugPrint('✅ Action logged successfully');
    } catch (e) {
      debugPrint('❌ Error logging action: $e');
    }
  }

  /// Clear local history (used when switching orders or logging out)
  void clearLocalHistory() {
    _currentOrderHistory = [];
    _historyError = null;
    notifyListeners();
  }
}
